-- Step 1: Add category_group column
ALTER TABLE rawdata_yellowpage_new
ADD COLUMN IF NOT EXISTS category_group VARCHAR(50);

-- Step 2: Update all categories with their groups

-- ============================================================
-- GROUP 1: Construction & Building
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Construction & Building'
WHERE category_name IN (
  'Builders & Building Contractors',
  'Bricklayers',
  'Building Consultants',
  'Building Contractors--Maintenance & Repairs',
  'Building Design - Extensions, Renovations & Alterations',
  'Building Designers',
  'Building Foundation & Excavation',
  'Building Information Centres',
  'Building Inspection',
  'Building Management Services & Consultants',
  'Building Restoration',
  'Building Societies',
  'Building Supplies',
  'Building Surveyors',
  'Buildings - Prefabricated & Transportable - Domestic',
  'Built In Wardrobes',
  'Carpenters & Joiners',
  'Carports & Pergolas',
  'Ceilings',
  'Cement Supplies',
  'Civil & Road Contractors',
  'Commercial & Industrial Cladding',
  'Concrete Aggregates',
  'Concrete Contractors',
  'Concrete Cutting, Grinding & Drilling',
  'Concrete Formwork, Form Ties & Accessories',
  'Concrete Gutters & Kerbs',
  'Concrete Paving',
  'Concrete Products',
  'Concrete Pumping',
  'Concrete Resurfacing & Repair',
  'Concrete Slab Floors',
  'Concrete Sleepers, Reinforcements & Mesh',
  'Construction Management',
  'Contractors--General',
  'Decking Contractors & Builders',
  'Demolition Contractors',
  'Draftsman & Drafting Services',
  'Driveways',
  'Fibre Cement Building Products',
  'Garage Builders & Prefabricators',
  'House Cladding',
  'House Planning',
  'House Relocation',
  'House Restumping & Reblocking',
  'Joinery',
  'Lattice',
  'Partitions & Fitouts',
  'Patio Builders',
  'Pile Driving Contractors & Equipment',
  'Portable & Transportable Buildings',
  'Precast Concrete Panels',
  'Ready Mix Concrete',
  'Rendering',
  'Retaining Walls',
  'Road Building Machinery',
  'Road Signs & Line Marking',
  'Roof Restoration & Repairs',
  'Roof Tiles',
  'Roof Trusses & Wall Frames',
  'Roofing Construction & Services',
  'Roofing Materials',
  'Rural & Industrial Sheds',
  'Scaffolding',
  'Second Hand Building Materials',
  'Shop Fittings & Office Fit Outs',
  'Solid Plastering',
  'Staircases & Handrails',
  'Steel Fabrication & Supplies',
  'Steel Supplies & Merchants',
  'Stonemasons & Stonework',
  'Structural Engineers',
  'Timber Supplies',
  'Timber Treatment & Preservation',
  'Timber Wholesale',
  'Underpinning Services',
  'Verandahs',
  'Wood & Plastic Moulding'
);

-- ============================================================
-- GROUP 2: Trades & Home Services
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Trades & Home Services'
WHERE category_name IN (
  'Air Conditioning Installation & Service',
  'Air Conditioning Parts',
  'Air Conditioning Wholesalers & Manufacturers',
  'Alarm Systems & Burglar Alarms',
  'Aluminium Fabricators',
  'Aluminium Manufacturers & Suppliers',
  'Aluminium Suppliers',
  'Aluminium Windows',
  'Asbestos Removal',
  'Asphalt & Bitumen Paving',
  'Asphalt Products & Supplies',
  'Balustrading',
  'Bath Resurfacing',
  'Bathroom Accessories & Equipment',
  'Bathroom Equipment & Accessories Wholesalers & Manufacturers',
  'Bathroom Renovations & Designs',
  'Blinds Cleaning & Repair',
  'Boring & Drilling Contractors',
  'Brick Cleaning',
  'Brick Paving',
  'Bricks',
  'Cabinet Makers & Designers',
  'Cabinet Making Supplies',
  'Carpet & Carpet Tiles Wholesalers & Manufacturers',
  'Carpet & Rug Overlocking Services',
  'Carpet Cleaning & Protection',
  'Carpet Layers & Planners',
  'Carpet Repair',
  'Carpets & Rugs--Dyeing',
  'CCTV & Security Cameras',
  'Chimney Sweep',
  'Clean Room Installation & Maintenance',
  'Cleaning Cloth Supplies',
  'Cleaning Products & Supplies',
  'Commercial & Industrial Cleaning Services',
  'Commercial Building Maintenance',
  'Cool Room Builders & Construction',
  'Curtain Cleaning & Maintenance',
  'Domestic Services',
  'Door & Gate Operating Equipment',
  'Doors & Door Fittings',
  'Drainage & Drain Contractors',
  'Drainage Equipment & Systems',
  'Duct Cleaning',
  'Ducting & Ductwork',
  'Dust & Fume Extraction Systems',
  'Electric Power Lines',
  'Electrical Accessories Wholesalers & Manufacturers',
  'Electrical Appliance Wholesalers & Manufacturers',
  'Electrical Appliances Services & Parts',
  'Electrical Engineers',
  'Electrical Switchboard Manufacturers',
  'Electrical Switches & Control Equipment',
  'Electrical Test & Tag',
  'Electrical Testing Equipment',
  'Electrical Wholesalers',
  'Electricians & Electrical Contractors',
  'Electricity Suppliers',
  'Emergency Lighting & Power',
  'Erosion Control & Soil Stabilisation',
  'Fencing Contractors',
  'Fencing Materials',
  'Floor Covering Layers',
  'Floor Machines',
  'Floor Tiles & Wall Tiles',
  'Floor Treatment Products',
  'Fly Screens',
  'Gas Appliances',
  'Gas Burners',
  'Gas Cylinder Testing',
  'Gas, Oil & Fuel Companies',
  'Gates',
  'Gazebos & Shade Houses',
  'Glass Bricks & Accessories',
  'Glass Manufacturing & Processing',
  'Glazier & Glass Replacement Services',
  'Graffiti Removal',
  'Grease Trap Cleaning Services',
  'Gutter Cleaning',
  'Guttering & Spouting',
  'Heating Appliances & Systems',
  'Heating Appliances Repair & Service',
  'Home Air Conditioning',
  'Home Automation',
  'Home Cleaning',
  'Home Improvements',
  'Home Maintenance & Handymen',
  'Hot Water Systems',
  'Insulation Installers & Contractors',
  'Interior Decorators',
  'Interior Designers',
  'Ironing Services',
  'Kitchen Renovations & Designs',
  'Leadlight',
  'Lift Maintenance',
  'Lighting Consultants',
  'Lighting Maintenance',
  'Lighting Stores',
  'Lighting Wholesalers & Manufacturers',
  'Lightning & Surge Protection',
  'Lighting & Power Pole',
  'Lock Distributors & Manufacturers',
  'Locksmiths & Locksmith Services',
  'Locksmiths'' Supplies',
  'Mattress Cleaning',
  'Mirrors',
  'Organising Services--Home & Office',
  'Painters & Decorators',
  'Painters'' Supplies',
  'Paint & Painting Equipment',
  'Parquetry Flooring',
  'Pest Control',
  'Pipe Lining & Coating',
  'Plaster & Plastering Supplies',
  'Plasterers',
  'Plastering Supplies & Equipment',
  'Plumbers & Gas Fitters',
  'Plumbing Consultants',
  'Plumbing Supplies',
  'Pressure & Steam Cleaning Contractors',
  'Pressure & Steam Cleaning Equipment',
  'Protective Coatings',
  'Refrigeration Domestic & Retail',
  'Refrigeration Engineers',
  'Retail Insulation Materials',
  'Rising Damp - Repairs & Waterproofing',
  'Roller Shutters',
  'Safety Glass',
  'Security Doors, Windows & Equipment',
  'Security Guards',
  'Security Systems',
  'Septic Tank Cleaning',
  'Septic Tank Installation & Manufacturers',
  'Sewage & Waste Water Treatment',
  'Sewer Cleaning Equipment',
  'Shower Screens',
  'Skylights',
  'Slaters & Roof Tilers',
  'Soundproofing & Acoustic Insulation Services',
  'Splashbacks',
  'Stained Glass',
  'Swimming Pool Designs & Construction',
  'Swimming Pool Maintenance & Repairs',
  'Swimming Pool Safety Inspections',
  'Tennis Court Construction & Repairs',
  'Tiling Equipment & Supplies',
  'Timber Windows',
  'Ventilation System & Equipment',
  'Wall & Floor Tilers',
  'Wall Finishes',
  'Wallpapering & Wallcovering Services',
  'Water Tanks & Tank Supplies',
  'Water Treatment & Equipment',
  'Waterproofing Contractors',
  'Window Cleaning',
  'Window Repairs',
  'Window Tinting',
  'Windows--Steel',
  'Commercial Air Conditioning',
  'Commercial Kitchen Equipment',
  'Commercial & Industrial Refrigeration',
  'Range Hoods',
  'Stoves & Ranges',
  'Stove & Rangehood Parts & Service'
);

-- ============================================================
-- GROUP 3: Automotive
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Automotive'
WHERE category_name IN (
  '4WD & 4X4 Accessories',
  'Auto Electrician Services',
  'Auto Wreckers & Recyclers',
  'Brake & Clutch Services',
  'Brakes & Clutch Equipment Wholesalers & Manufacturers',
  'Car & Automotive Transmissions',
  'Car Accessories',
  'Car Air Conditioning',
  'Car Alarms',
  'Car Auctions',
  'Car Audio, Stereo & Radio',
  'Car Batteries & Car Battery Replacements',
  'Car Cleaning Products',
  'Car Detailing',
  'Car Driving &/or Pooling Services',
  'Car Insurance Providers',
  'Car Loans & Motor Vehicle Finance',
  'Car Paint',
  'Car Parking',
  'Car Parts',
  'Car Radiator Repair & Services',
  'Car Rental & Hire',
  'Car Restoration',
  'Car Transport',
  'Car Wash Services',
  'Caravan & Camper Trailer Repairs',
  'Diesel Engineers',
  'Diesel Engines, Parts & Equipment',
  'Diesel Fuel Injection',
  'Electronic Rust Protection & Rustproofing',
  'Engine Reconditioning',
  'Exhaust Systems & Mufflers',
  'Fuel Pumps & Carburettor Equipment',
  'LPG & Gas Conversions',
  'Mechanics & Motor Engineers',
  'Motor Body Builders',
  'Motor Vehicle Leasing',
  'Motorcycle Parts & Accessories Retailers',
  'Motorcycle Parts & Accessory Wholesalers & Manufacturers',
  'Motorcycle Tours & Hire',
  'Motorcycle Wreckers',
  'Motorsport Services',
  'New Car Dealers',
  'Panel Beater & Painters',
  'Panel Beating Supplies & Equipment',
  'Petrol Engines',
  'Petrol Fuel Injection',
  'Power Steering',
  'Roadside Assistance',
  'Service Stations',
  'Suspension, Shock Absorbers & Springs',
  'Towing Equipment',
  'Towing Services',
  'Truck & Bus Sales',
  'Truck Hire & Bus Hire',
  'Truck Parts',
  'Turbochargers',
  'Tyre Repairs, Retreading & Recapping',
  'Tyres',
  'Tyres--Retreading, Repairing &/or Changing Equipment',
  'Used Cars',
  'Vehicle Inspections',
  'Wheel Alignment & Wheel Balance',
  'Wheels & Rims',
  'Windscreens & Windscreen Repair',
  'Bus & Coach Charter & Tours',
  'Bus & Truck Repairs',
  'Bus Builders'
);

-- ============================================================
-- GROUP 4: Healthcare & Medical
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Healthcare & Medical'
WHERE category_name IN (
  'Anaesthesia',
  'Audiologist & Hearing Test',
  'Bariatric Surgery',
  'Cardiology',
  'Community Health Centres & Services',
  'Dental Equipment--Repairs',
  'Dental Health Aids',
  'Dental Hospital & Emergency Dental',
  'Dental Laboratories',
  'Dental Prosthetist',
  'Dental Supplies & Equipment',
  'Dental Technicians',
  'Dentist',
  'Dermatology',
  'Diagnostic Radiology',
  'Diagnostic Ultrasound',
  'Doctors-Medical Practitioners',
  'Endocrinology',
  'Endodontists',
  'Gastroenterology',
  'Gynaecological Oncology',
  'Hand Surgery',
  'Health Insurance',
  'Health Support Organisations',
  'Hire--Medical Equipment',
  'Home Health Care Equipment',
  'Hospitals--Public',
  'Infertility Services (Including IVF)',
  'Medical Agents',
  'Medical Centres',
  'Medical Equipment & Repairs',
  'Medical Oncology',
  'Medical Research',
  'Medical Supplies',
  'Obstetrics & Gynaecology',
  'Occupational & Environmental Medicine',
  'Ophthalmology',
  'Optical Prescription Dispensers',
  'Optical Supplies',
  'Optometrist',
  'Oral & Maxillofacial Surgeons (Dental)',
  'Oral Pathology & Oral Medicine Specialists',
  'Oral Surgeons',
  'Orthodontist',
  'Orthodontists (Specialty)',
  'Orthopaedic Footwear & Custom Shoes',
  'Orthopaedic Surgery',
  'Otolaryngology (Ear, Nose & Throat)',
  'Paediatric Dentists',
  'Paediatric Medicine',
  'Palliative Care',
  'Pathology Laboratories',
  'Periodontists',
  'Pharmaceutical Products Wholesalers & Manufacturers',
  'Pharmacists--Consultant',
  'Plastic & Reconstructive Surgery',
  'Private Hospitals',
  'Prosthodontists',
  'Psychiatry',
  'Rehabilitation Medicine',
  'Rehabilitation Services',
  'Skin Cancer Clinic',
  'Sports Medicine',
  'Surgery-General',
  'Travel Health',
  'Urology',
  'Vascular Surgery',
  'Chemist & Pharmacy Stores',
  'Chemists--Consulting & Industrial',
  'Chemists'' Supplies',
  'X-Ray Equipment & Supplies',
  'Vets & Veterinary Surgeons',
  'Veterinary Animal Clinics & Hospitals',
  'Veterinary Laboratories',
  'Veterinary Supplies & Instruments'
);

-- ============================================================
-- GROUP 5: Allied Health & Wellness
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Allied Health & Wellness'
WHERE category_name IN (
  'Acupuncture',
  'Alcohol & Drug Counselling',
  'Alternative & Natural Therapies',
  'Alternative Health Therapies Courses',
  'Aromatherapy',
  'Bowen Therapy',
  'Chinese Medicine',
  'Chiropractor',
  'Colonic Irrigation',
  'Dietitians',
  'Exercise Physiologists',
  'Feldenkrais',
  'Health & Fitness - Centres & Services',
  'Health Food Stores',
  'Health Foods & Products Wholesalers & Manufacturers',
  'Herbalists',
  'Homeopathy',
  'Kinesiology',
  'Life Coach',
  'Massage Tables & Equipment',
  'Massage Therapy',
  'Massage Therapy Courses',
  'Meditation',
  'Myotherapy',
  'Naturopaths',
  'Occupational Therapist',
  'Osteopath',
  'Physiotherapist',
  'Physiotherapy Equipment',
  'Pilates',
  'Podiatrist',
  'Podiatry Supplies',
  'Psychologist',
  'Psychotherapists',
  'Reflexology',
  'Reiki',
  'Relaxation Therapy',
  'Shiatsu Therapy',
  'Skin Treatments & Skin Clinics',
  'Vitamin Products',
  'Weight Loss Treatments',
  'Marriage, Family & Personal Counselling'
);

-- ============================================================
-- GROUP 6: Beauty & Personal Care
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Beauty & Personal Care'
WHERE category_name IN (
  'Artificial Nails',
  'Barbers & Barber Shops',
  'Beauty Courses',
  'Beauty Salon Supplies & Equipment',
  'Beauty Salons',
  'Body & Ear Piercing',
  'Cosmetic Store',
  'Cosmetic Surgery',
  'Day Spas',
  'Hair Care Products',
  'Hair Removal',
  'Hair Treatment & Replacement',
  'Hairdressers',
  'Hairdressing Courses',
  'Hairdressing Supplies',
  'Make-Up Artists & Supplies',
  'Spray Tanning',
  'Sunglasses',
  'Tattoo Removal'
);

-- ============================================================
-- GROUP 7: Food & Hospitality
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Food & Hospitality'
WHERE category_name IN (
  'Bakers',
  'Bakery Equipment',
  'Bars',
  'Bars--Domestic & Commercial',
  'Bottle Shop & Liquor Store',
  'Butcher Supplies',
  'Butchers Shop',
  'Cafes',
  'Cake & Pastry Shops',
  'Cake Decorating Supplies',
  'Cake Decorators & Decorating Classes',
  'Catering',
  'Catering & Food Consultants',
  'Catering Equipment Hire',
  'Catering Supplies',
  'Chocolate & Cocoa',
  'Coffee Retailers',
  'Confectionery & Lolly Shop',
  'Delicatessens',
  'Dishwasher Service & Parts',
  'Dishwashers',
  'Dispensing Equipment, Supplies & Service',
  'Egg Merchants',
  'Fast Food',
  'Fish & Seafood',
  'Fish & Seafood Production &/or Processing',
  'Food &/or General Store Supplies',
  'Food &/or General Stores',
  'Food Brokers & Agents',
  'Food Delicacies',
  'Food Product Processors & Manufacturers',
  'Frozen Food Wholesalers & Manufacturers',
  'Frozen Foods--Retail',
  'Fruit &/or Berry Growers',
  'Fruit Shops & Greengrocers',
  'Hotel & Motel Brokers',
  'Hotel, Bar & Restaurant Supplies',
  'Hotels & Accommodation',
  'Ice Cream--Retail',
  'Ice Making Machine',
  'Meat Pies',
  'Milk Vendors',
  'Motel Supplies & Equipment',
  'Motels',
  'Organic Products',
  'Oyster Suppliers & Farmers',
  'Pizza Restaurants',
  'Poultry--Retail',
  'Pubs',
  'Restaurants',
  'Smallgoods Wholesalers & Manufacturers',
  'Supermarkets & Grocery Stores',
  'Theatre Restaurants',
  'Wholesale Butchers',
  'Wholesale Cakes & Pastries',
  'Wholesale Coffee',
  'Wholesale Grain & Produce',
  'Wholesale Seafood & Fish',
  'Wine Merchants & Spirit Dealers',
  'Wine Racks & Storage',
  'Wineries & Vineyards'
);

-- ============================================================
-- GROUP 8: Retail & Shopping
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Retail & Shopping'
WHERE category_name IN (
  'Antiques - Auctions & Dealers',
  'Antiques Reproduction & Restoration',
  'Aquariums & Aquarium Supplies',
  'Art Dealers',
  'Art Supplies',
  'Artificial Flowers & Plants',
  'Baby Prams, Furniture & Accessories',
  'BBQ & Barbecue Equipment',
  'Beds & Bedding Stores',
  'Bicycle Accessories & Repairs',
  'Bicycles & Accessories Wholesalers & Manufacturers',
  'Book Stores & Shops',
  'Books Online',
  'Boutiques',
  'Bridal Dresses & Accessories',
  'Camping Gear & Outdoor Equipment',
  'Camper Trailers & Caravans',
  'Camper Trailers & Caravan Hire',
  'Campervans & Motor Homes',
  'Caravan Parks',
  'Christmas Trees & Decorations',
  'Clocks & Repairs',
  'Clothes Online',
  'Clothing Alterations & Mending',
  'Clothing Pattern Services',
  'Clothing--Custom Made',
  'Coin & Note Changing Equipment',
  'Craft Supplies & Craft Shop',
  'Department Stores',
  'Discount Stores',
  'Dress Patterns & Dressmakers'' Models',
  'Dressmakers',
  'Electrical & Home Appliance Stores',
  'Embroidery',
  'Embroidery Supplies & Equipment',
  'Fabrics-Knitted or Woven',
  'Fashion Accessories',
  'Fashion Agents',
  'Fashion Jewellery',
  'Fireplaces & Fireplace Accessories',
  'Fitness Equipment',
  'Florist Supplies',
  'Florists',
  'Furnishings--Retail',
  'Furnishings--W''sale',
  'Furniture & Appliance Hire',
  'Furniture Assembly Services',
  'Furniture Design & Custom Furniture',
  'Furniture Manufacturers & Wholesalers',
  'Furniture Manufacturers Supplies',
  'Furniture Restoration & Repairs',
  'Furniture Stores & Shops',
  'Gem Merchants',
  'Gift Baskets & Hampers',
  'Gift Shop',
  'Gift Shop Supplies',
  'Gold & Silver Merchants',
  'Hardware Store',
  'Hardware--W''sale',
  'Hi-Fi Equipment',
  'Hi-Fi Equipment & Service',
  'Home Cinema & Theatre',
  'Jewellery Designers',
  'Jewellery Stores',
  'Jewellery Valuation',
  'Ladies'' Wear-Retail',
  'Lottery Agents',
  'Mattresses',
  'Microwave Oven',
  'Mobile Phones & Accessories',
  'Mobile Phone Repairs & Service',
  'Music & Musical Instruments',
  'Music Stores-Retail',
  'Musical Instrument Makers & Repairers',
  'Newsagents',
  'Office & Business Systems',
  'Office Furniture',
  'Office Supplies',
  'Opals',
  'Oriental Rugs & Handmade Carpets',
  'Outdoor Furniture',
  'Pawn Shop & Pawnbrokers',
  'Pet Shops'' Suppliers',
  'Pet Supplies & Pet Food',
  'Pet Warehouse - Shops & Stores',
  'Pianos, Keyboards & Organs',
  'Point of Sale (POS) Systems & Service',
  'Recycled Clothing',
  'Second Hand Books & Antiquarian',
  'Second Hand Dealers',
  'Second Hand Furniture',
  'Sewing Machines',
  'Sewing Machine Repairs & Service',
  'Shopping Centres & Malls',
  'Signwriters',
  'Sports Equipment, Goods & Repairs',
  'Stamp Collectors & Dealers',
  'Stationery',
  'Tailors--Ladies''',
  'Tailors-Men''s',
  'Television Retailers',
  'Toys--Retail & Repairs',
  'Toy Manufacturers',
  'TV Antenna Services',
  'TV Hire',
  'TV Repairs & Installation',
  'Vacuum Cleaner Parts & Repairs',
  'Vacuum Cleaners',
  'Video & DVD Equipment--Repairs & Service',
  'Washing Machines & Dryer Repairs, Service & Parts',
  'Washing Machines & Dryers - Commercial & Industrial',
  'Washing Machines & Dryers - Domestic',
  'Watch Shop & Watch Repairs',
  'Watches--W''sale',
  'Watchmakers'' Equipment & Supplies',
  'Wholesale Florist',
  'Wholesale Jewellery',
  'Wholesale Toys',
  'Wholesale Tyres',
  'Neon & LED Signs',
  'New Age Products & Services',
  'Fridge Repairs'
);

-- ============================================================
-- GROUP 9: Professional Services
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Professional Services'
WHERE category_name IN (
  'Accountants & Auditors',
  'Architects',
  'Barristers (All states except TAS)',
  'Barristers & Solicitors (TAS only)',
  'Business & Professional Organisations',
  'Business Consultants',
  'Business Law',
  'Business Records Management',
  'Business Systems Consultants',
  'Civil Litigation',
  'Commercial Law',
  'Conveyancer & Conveyancing Services',
  'Conveyancing & Property Law',
  'Criminal Law',
  'Customs Brokers',
  'Debt Collection',
  'Engineering Consultants & Services',
  'Environmental Consultants',
  'Export Agents',
  'Family Law',
  'Financial Planning',
  'Forensic Services',
  'Franchises & Franchising',
  'Importers & Imported Products',
  'Insurance Agents',
  'Land Surveyors',
  'Lawyers & Solicitors',
  'Legal Support & Referral Services',
  'Management Consultants',
  'Marketing Consultants & Services',
  'Mediation',
  'Mediators',
  'Migration Agents & Services',
  'Packaging Consultants',
  'Patent Attorneys',
  'Personal Injury Lawyers',
  'Property Consultants',
  'Public Notary',
  'Retirement Planning & Advisory Services',
  'Settlement Agents (WA & NT only)',
  'Shelf Company Services',
  'Small Business Advisory Services',
  'Superannuation Fund, Annuity & Rollover Consultants',
  'Tax Agents',
  'Town & Regional Planning',
  'Trade Mark Registration & Investigation',
  'Trademark Attorneys',
  'Trustee Services',
  'Wills, Probates & Estates',
  'Workers Compensation'
);

-- ============================================================
-- GROUP 10: Real Estate & Property
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Real Estate & Property'
WHERE category_name IN (
  'Apartments & Flats',
  'B&B - Bed & Breakfast Accommodation',
  'Backpackers Accommodation',
  'Guest Houses',
  'Holidays & Resorts',
  'Real Estate Development',
  'Relocation Consultants & Services',
  'Serviced Apartments',
  'Storage Solutions',
  'Warehousing',
  'Accommodation Booking & Inquiry Services'
);

-- ============================================================
-- GROUP 11: Transport & Logistics
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Transport & Logistics'
WHERE category_name IN (
  'Air Cargo Services',
  'Aircraft Charter & Hire',
  'Airlines & Travel Agents',
  'Airport Bus & Shuttles',
  'Airports &/or Airport Services',
  'Armoured Car Services',
  'Boat & Yacht Transport Services',
  'Cold Storage',
  'Courier Services',
  'Crane Hire',
  'Elevated Work Platform Hire',
  'Forklift Licence & Plant Operator Training',
  'Forklifts & Forklift Repairs',
  'Freight & Cargo Services',
  'Freight & Transport Companies',
  'Furniture Removalists & Movers',
  'Heavy Haulage',
  'Helicopters',
  'Limo Hire',
  'Pallets & Platforms',
  'Piano Removals',
  'Railway Construction, Equipment & Materials',
  'Railway Services',
  'Refrigerated Transport Services',
  'Refrigerated Transport Vans & Trucks',
  'Road Transport Vehicles &/or Equipment',
  'Shipping Agents & Freight Companies',
  'Storage--Liquid--Bulk',
  'Taxi',
  'Taxi Truck',
  'Tipper Truck Contractors',
  'Trailer Hire',
  'Transport - Light',
  'Transport Companies & Freight Forwarding Agents',
  'Transport Depots',
  'Transport Escort & Pilot Services',
  'Transportation Consultants',
  'Water Cartage',
  'Water Taxis'
);

-- ============================================================
-- GROUP 12: Agriculture & Rural
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Agriculture & Rural'
WHERE category_name IN (
  'Abattoirs',
  'Aerial Agricultural Services',
  'Animal & Pet Enclosures',
  'Animal Welfare',
  'Artificial Breeding Services',
  'Bird Breeders & Dealers',
  'Cattery',
  'Dog & Cat Clipping & Grooming',
  'Dog & Cat Minding - In Home',
  'Dog Boarding Kennels',
  'Dog Breeders',
  'Dog Training',
  'Dogs'' Supplies',
  'Emu & Ostrich Farmers & Products',
  'Farm & Agricultural Advisory Services',
  'Farm & Agricultural Machinery',
  'Farm Contracting Services',
  'Farm Supplies & Farming Equipment',
  'Farmers',
  'Fertiliser & Insecticide',
  'Fertilisers',
  'Game Farmers & Dealers',
  'Grain & Produce',
  'Graziers',
  'Herbs (Nurseries-Retail)',
  'Horse Dentists',
  'Horse Riding',
  'Horse Transport',
  'Horticultural Consultants',
  'Insect Control Equipment',
  'Insecticides, Herbicides & Fungicides',
  'Livestock Buyers',
  'Livestock Transport Services',
  'Pet Care',
  'Pet Cemetery & Crematorium',
  'Pet Transport Services',
  'Poultry Farmers & Dealers',
  'Poultry Supplies',
  'Saddlery & Riding',
  'Seed Cleaning, Drying & Grading',
  'Seed Suppliers',
  'Sheep Shearing Contractors',
  'Stock & Station Agents',
  'Stock Feeds, Fodder & Supplements',
  'Traps--Animal Or Rodent',
  'Weed Control Services',
  'Bee & Wasp Removal'
);

-- ============================================================
-- GROUP 13: Education & Training
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Education & Training'
WHERE category_name IN (
  'Advanced & Defensive Driving School',
  'Boat Licence Testing',
  'Business (Training & Development)',
  'Business Colleges',
  'Career Counselling',
  'Co-Educational Schools',
  'Driving Lessons & Schools',
  'Driving Training Equipment & Facilities',
  'Flying School',
  'Human Resources (Training & Development)',
  'Kindergartens & Pre-Schools',
  'School Supplies',
  'Schools',
  'Schools--Public (State) - NSW only',
  'Schools--State ( All States except NSW)',
  'Sewing & Dressmaking Tuition',
  'Surfing Instruction',
  'Training, Mentoring & Development',
  'Traffic Schools',
  'Vocational Education & Training (Training & Development)',
  'Music Teachers'
);

-- ============================================================
-- GROUP 14: Entertainment & Recreation
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Entertainment & Recreation'
WHERE category_name IN (
  'Adult Services & Entertainment',
  'Adult Shops & Stores',
  'Amusement Equipment & Hire',
  'Amusement Machines--Coin Operated',
  'Astrology',
  'AV Equipment & Production',
  'Boat & Yacht Builders & Repairers',
  'Boat & Yacht Equipment',
  'Boat Hire',
  'Boat Motors & Outboards',
  'Bowling Club',
  'Camps',
  'Cinemas',
  'Conference Venues',
  'Country Music Clubs',
  'Coursing & Kennel Clubs',
  'DJs - Mobile',
  'Event Management',
  'Fencing Clubs',
  'Fishing Bait',
  'Fishing Tackle',
  'Fishing Trips',
  'Function Rooms & Party Venues',
  'Gaming Machines & Supplies',
  'Go-Karts & Karting Supplies',
  'Golf Clubs - Private',
  'Golf Driving Range',
  'Internet Cafes',
  'Jukeboxes',
  'Jumping Castles Hire',
  'Lawn Mowing Services',
  'Lawn Mower Shops & Repairs',
  'Lawn Mowers Wholesalers & Manufacturers',
  'Garden Nurseries',
  'Garden Pots',
  'Garden Supplies & Equipment',
  'Gardeners',
  'Gardening Clubs',
  'Indoor Plant Hire',
  'Irrigation & Reticulation Systems',
  'Land Clearing & Firebreak Contractors',
  'Landscape Architects',
  'Landscape Supplies',
  'Landscaping & Landscape Design',
  'Music Amplification Equipment & Services',
  'Music Arrangers & Composers',
  'Music Therapists',
  'Music-Background',
  'Music-Sheet',
  'Musicians & Musicians'' Agents',
  'Organs & Keyboards-Tuning & Repairing',
  'Parks, Gardens & Reserves',
  'Party Balloons & Printed Balloons',
  'Party Equipment Hire',
  'Pay Television',
  'Personal Trainers & Fitness Training',
  'Piano Tuning & Piano Repair',
  'Pipe Organ Builders, Tuners & Restorers',
  'Psychic & Clairvoyant',
  'Public Address (PA) Sound Systems',
  'Public Golf Courses',
  'Publishers--Music',
  'Radio Communications Equipment & Service',
  'Roses',
  'Rugby League Clubs',
  'Satellite Equipment & Services',
  'Slashing Contractors',
  'Social & General Clubs',
  'Television Stations',
  'Theatres & Theatre Companies',
  'Tourist Attractions & Information',
  'Travel Agents',
  'Tree & Stump Removal Services',
  'Tree Surgery',
  'Turf & Lawn Suppliers',
  'Water Features, Ponds & Garden Ornaments',
  'Wedding Cakes',
  'Wedding Cars',
  'Wedding Flowers',
  'Wedding Gifts & Registry Services',
  'Wedding Hair & Beauty Services',
  'Wedding Jewellery & Accessories',
  'Wedding Music & Entertainment',
  'Wedding Photographers',
  'Wedding Planning & Planners',
  'Wedding Venues',
  'Arboriculturists',
  'Rotary Hoeing',
  'Nursery & Garden Supplies Wholesale',
  'Nursery Supplies',
  'Advanced Shrubs & Trees (Nurseries-Retail)'
);

-- ============================================================
-- GROUP 15: Industrial & Manufacturing
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Industrial & Manufacturing'
WHERE category_name IN (
  'Abrasive Blasting',
  'Air & Gas Cylinders',
  'Automation Systems & Equipment',
  'Balancing Equipment & Services',
  'Battery Charging Equipment',
  'Bearings & Bushings',
  'Bitumen Spraying',
  'Chainsaws & Brush Cutters',
  'Coach & Carriage Builders & Dealers',
  'Communication Antennas',
  'Compressed Air Control Equipment',
  'Computer Laptop Hire & Leasing',
  'Computer Networking & Installation',
  'Computer Parts & Equipment',
  'Cork Merchants',
  'Crushers & Crushing Services',
  'Data Communications',
  'Designing Engineers',
  'Distilled Water',
  'Drinking Water Supplies & Accessories',
  'Electric Motor Repairs & Generator Repairs',
  'Electric Motors',
  'Engineering & Engineers',
  'Engineering & Mining Surveyors',
  'Engineering Supplies',
  'Ergonomics',
  'Excavation & Earth Moving Equipment',
  'Excavation & Earthmoving Contractors',
  'Factory & Workshop Equipment Hire',
  'Fans & Blowers',
  'Fax Equipment, Supplies & Service',
  'Fibre & Cardboard Boxes',
  'Fibre Optics',
  'Filtering Materials & Supplies',
  'Filters & Filter Service',
  'Firewood',
  'Generators',
  'Glass Processing & Handling Equipment',
  'Glass Washing Machines',
  'Hoses & Hose Fittings',
  'Hydraulic Equipment & Supplies',
  'Hydroponics & Hydroponic Equipment',
  'Industrial Capacitors',
  'Industrial Drying Equipment & Services',
  'Industrial Sewing Machines',
  'Inspection & Testing Services',
  'Installation & Maintenance Engineers',
  'Instrument Cases',
  'Internet Marketing Services',
  'Jacks',
  'Ladders, Step Ladders & Trestles',
  'Laser Cutting Services',
  'Laundries',
  'Laundromat & Self Service Laundries',
  'Commercial Laundry Equipment & Supplies',
  'Linen Hire',
  'Lime',
  'Mailing Machines & Equipment',
  'Manufacturers'' Agents',
  'Manufacturing Engineers',
  'Marble & Granite Suppliers',
  'Marine Engineers',
  'Measuring Machines & Equipment',
  'Mechanical Engineer',
  'Metal Polishing',
  'Metal Recyclers & Merchants',
  'Mining Contractors',
  'Mining, Quarrying Equipment & Supplies',
  'Mobile Marketing',
  'Natural Stone Products & Supplies',
  'Nuts & Bolts',
  'OHS - Occupational Health & Safety',
  'Oil & Mechanical Seals',
  'Overall Hire Services',
  'Packaging Supplies & Materials',
  'Particle Board',
  'Plastic Bags',
  'Plastic Fabrication',
  'Plywood & Veneers',
  'Portable Toilets',
  'Post Hole Contractors & Equipment',
  'Power Tools & Repairs',
  'Printers & Printing Services',
  'Pump Manufacturers, Sales & Service',
  'Pumping Contractors',
  'Quarries',
  'Rechargeable Batteries & Dry Cell Battery',
  'Recycling & Waste Management Equipment',
  'Recycling Depots Beverage Containers ( S.A. & NT. Only )',
  'Recycling Services',
  'Refrigeration Parts & Equipment Wholesaler & Manufacturer',
  'Rubber Products',
  'Rubbish Removal & Skip Bins',
  'Safes & Vaults',
  'Sand, Soil & Gravel Supplies',
  'Sand, Soil & Gravel Wholesalers',
  'Sawdust & Shaving Suppliers',
  'Sawmills',
  'Saws',
  'Scrap Metal Merchants',
  'Sealing Compounds & Services',
  'Second Hand Cardboard Boxes & Cartons',
  'Second Hand Machinery',
  'Sewing Contractors--Industrial',
  'Sharpening Service',
  'Shavers',
  'Shavers -- Electric -- Repairs',
  'Sheet Metal Fabricators',
  'Shelving Solutions',
  'Shelving Units & Racks',
  'Ship Builders & Repairers',
  'Soil Testing',
  'Solar Energy',
  'Spray Painting',
  'Stainless Steel Products & Equipment Suppliers',
  'Steel Wool Wholesalers & Manufacturers',
  'Tank Cleaning',
  'Tarpaulins',
  'Telephone Installation, Repairs & Maintenance',
  'Telephone Systems & Equipment',
  'Telephones & Accessories',
  'Timber Logging',
  'Tools & Trade Tools',
  'Underground Penetrating Radar & Locators',
  'Vending Machines',
  'Waste Disposal & Reduction Services',
  'Water Coolers',
  'Welding',
  'Welding Supplies & Equipment',
  'Wood Benders & Carvers',
  'Wood Chippers',
  'Wooden Boxes & Cases',
  'Work & Corporate Uniform Hire',
  'Disposable Paper Products',
  'Document Shredding',
  'Nurses & Nursing Services',
  'Aged Care Services & Homes',
  'Disability Services & Care Organisations',
  'Hire--Nursery Equipment',
  'Nappy Services'
);

-- ============================================================
-- Catch-all: Assign remaining uncategorized to 'Other'
-- ============================================================
UPDATE rawdata_yellowpage_new
SET category_group = 'Other'
WHERE category_group IS NULL;

-- ============================================================
-- Step 3: Add index for query performance
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_category_group ON rawdata_yellowpage_new(category_group);

-- ============================================================
-- Verification: Check distribution
-- ============================================================
SELECT category_group, COUNT(*) as count
FROM rawdata_yellowpage_new
GROUP BY category_group
ORDER BY count DESC;
