import type { Tour } from 'nextstepjs';

export const tours: Tour[] = [
  {
    tour: 'sidebar-tour',
    steps: [
      {
        icon: '🔍',
        title: 'Leads',
        content: 'Search 50,000+ Australian businesses and filter by city, industry, and more to find your ideal prospects.',
        selector: '#sidebar-nav-leads',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📁',
        title: 'Collections',
        content: 'Save selected businesses into named lists. These become the recipient lists for your campaigns.',
        selector: '#sidebar-nav-collections',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '✉️',
        title: 'Campaigns',
        content: 'Create AI-powered email campaigns, generate personalized emails, and send them to your collections.',
        selector: '#sidebar-nav-campaigns',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📤',
        title: 'Senders',
        content: 'Connect a Gmail or Outlook account, or verify a custom domain to use as your sending address.',
        selector: '#sidebar-nav-senders',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📊',
        title: 'Analytics',
        content: 'Track open rates, clicks, and overall campaign performance over time.',
        selector: '#sidebar-nav-analytics',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '⚙️',
        title: 'Settings',
        content: 'Manage your account, organization details, and platform preferences.',
        selector: '#sidebar-nav-settings',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
    ],
  },
];
