import type { Tour } from 'nextstepjs';

export const tours: Tour[] = [
  {
    tour: 'sidebar-tour',
    steps: [
      {
        icon: '🔍',
        title: 'Leads',
        content: 'Search 50,000+ Australian businesses and filter by city, industry, and more to find your ideal prospects.',
        selector: '#sidebar-nav-leads',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📁',
        title: 'Collections',
        content: 'Save selected businesses into named lists. These become the recipient lists for your campaigns.',
        selector: '#sidebar-nav-collections',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '✉️',
        title: 'Campaigns',
        content: 'Create AI-powered email campaigns, generate personalized emails, and send them to your collections.',
        selector: '#sidebar-nav-campaigns',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📤',
        title: 'Senders',
        content: 'Connect a Gmail or Outlook account, or verify a custom domain to use as your sending address.',
        selector: '#sidebar-nav-senders',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📊',
        title: 'Analytics',
        content: 'Track open rates, clicks, and overall campaign performance over time.',
        selector: '#sidebar-nav-analytics',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '⚙️',
        title: 'Settings',
        content: 'Manage your account, organization details, and platform preferences.',
        selector: '#sidebar-nav-settings',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
    ],
  },
  {
    tour: 'senders-tour',
    steps: [
      {
        icon: '✉️',
        title: 'Welcome to Senders',
        content: "This page manages the email addresses you send campaigns from. Let's get you set up.",
        selector: '#senders-header',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '➕',
        title: 'Add a Sender',
        content: 'Click here to connect a Gmail/Outlook account or verify a custom domain.',
        selector: '#senders-add-button',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '✅',
        title: 'Your Senders',
        content: 'All connected senders appear in this table. You can set a default sender for all campaigns.',
        selector: '#senders-table-card',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
    ],
  },
  {
    tour: 'leads-tour',
    steps: [
      {
        icon: '🔍',
        title: 'Search Australian Businesses',
        content: 'Use these filters to find your ideal prospects from 50,000+ Australian businesses.',
        selector: '#leads-filters-bar',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🏢',
        title: 'Search by Name',
        content: 'Type a company name here to search.',
        selector: '#leads-search-input',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🏭',
        title: 'Filter by Industry',
        content: 'Narrow results to your target industry.',
        selector: '#leads-industry-filter',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📋',
        title: 'Browse Results',
        content: "Results appear here. Click a row's checkbox to select it.",
        selector: '#leads-results-summary',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
    ],
  },
  {
    tour: 'collections-tour',
    steps: [
      {
        icon: '📁',
        title: 'Collections',
        content: 'Collections are saved groups of businesses. They become the recipient lists for your campaigns.',
        selector: '#collections-header',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '➕',
        title: 'Create Collections from Leads',
        content: 'Go to the Leads page, select businesses, then save them to a collection.',
        selector: '#collections-create-button',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🗂️',
        title: 'Your Collections',
        content: 'Collections appear here as cards. Click one to view and manage the businesses inside.',
        selector: '#collections-header',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
    ],
  },
  {
    tour: 'create-campaign-tour',
    steps: [
      {
        icon: '👥',
        title: 'Choose Recipients',
        content: 'Select the collections whose businesses will receive this campaign.',
        selector: '#campaign-recipients-card',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🎯',
        title: 'Pick a Collection',
        content: 'Click a collection capsule to include all its businesses as recipients.',
        selector: '#campaign-collections-picker',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📝',
        title: 'Campaign Name',
        content: 'Give your campaign a clear, descriptive name.',
        selector: '#campaign-name-input',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '💡',
        title: 'Describe Your Service',
        content: 'The AI uses this to write personalized emails. Be specific — more detail means better emails.',
        selector: '#campaign-service-description',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🎭',
        title: 'Choose a Tone',
        content: 'Select the tone that matches your brand voice.',
        selector: '#campaign-tone-select',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🚀',
        title: 'Create the Campaign',
        content: "Click here to save the campaign. You'll then be able to start AI email generation.",
        selector: '#campaign-submit-button',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
    ],
  },
  {
    tour: 'campaign-detail-tour',
    steps: [
      {
        icon: '🤖',
        title: 'Generate Emails with AI',
        content: 'Click here to have the AI write a personalized email for each recipient in your collection.',
        selector: '#campaign-start-generation-button',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📊',
        title: 'Track Progress',
        content: 'The progress bar updates automatically as emails are generated. No need to refresh.',
        selector: '#campaign-progress-area',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📧',
        title: 'Review Emails',
        content: 'Each generated email appears here. Expand any email to read its content before sending.',
        selector: '#campaign-emails-section',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
    ],
  },
];
