-- GROUP 1: Construction & Building
UPDATE rawdata_yellowpage_new
SET category_group = 'Construction & Building'
WHERE category_name IN (
  'Builders & Building Contractors',
  'Bricklayers',
  'Building Consultants',
  'Building Contractors--Maintenance & Repairs',
  'Building Design - Extensions, Renovations & Alterations',
  'Building Designers',
  'Building Foundation & Excavation',
  'Building Information Centres',
  'Building Inspection',
  'Building Management Services & Consultants',
  'Building Restoration',
  'Building Societies',
  'Building Supplies',
  'Building Surveyors',
  'Buildings - Prefabricated & Transportable - Domestic',
  'Built In Wardrobes',
  'Carpenters & Joiners',
  'Carports & Pergolas',
  'Ceilings',
  'Cement Supplies',
  'Civil & Road Contractors',
  'Commercial & Industrial Cladding',
  'Concrete Aggregates',
  'Concrete Contractors',
  'Concrete Cutting, Grinding & Drilling',
  'Concrete Formwork, Form Ties & Accessories',
  'Concrete Gutters & Kerbs',
  'Concrete Paving',
  'Concrete Products',
  'Concrete Pumping',
  'Concrete Resurfacing & Repair',
  'Concrete Slab Floors',
  'Concrete Sleepers, Reinforcements & Mesh',
  'Construction Management',
  'Contractors--General',
  'Decking Contractors & Builders',
  'Demolition Contractors',
  'Draftsman & Drafting Services',
  'Driveways',
  'Fibre Cement Building Products',
  'Garage Builders & Prefabricators',
  'House Cladding',
  'House Planning',
  'House Relocation',
  'House Restumping & Reblocking',
  'Joinery',
  'Lattice',
  'Partitions & Fitouts',
  'Patio Builders',
  'Pile Driving Contractors & Equipment',
  'Portable & Transportable Buildings',
  'Precast Concrete Panels',
  'Ready Mix Concrete',
  'Rendering',
  'Retaining Walls',
  'Road Building Machinery',
  'Road Signs & Line Marking',
  'Roof Restoration & Repairs',
  'Roof Tiles',
  'Roof Trusses & Wall Frames',
  'Roofing Construction & Services',
  'Roofing Materials',
  'Rural & Industrial Sheds',
  'Scaffolding',
  'Second Hand Building Materials',
  'Shop Fittings & Office Fit Outs',
  'Solid Plastering',
  'Staircases & Handrails',
  'Steel Fabrication & Supplies',
  'Steel Supplies & Merchants',
  'Stonemasons & Stonework',
  'Structural Engineers',
  'Timber Supplies',
  'Timber Treatment & Preservation',
  'Timber Wholesale',
  'Underpinning Services',
  'Verandahs',
  'Wood & Plastic Moulding'
);
