-- GROUP 2: Trades & Home Services
UPDATE rawdata_yellowpage_new
SET category_group = 'Trades & Home Services'
WHERE category_name IN (
  'Air Conditioning Installation & Service',
  'Air Conditioning Parts',
  'Air Conditioning Wholesalers & Manufacturers',
  'Alarm Systems & Burglar Alarms',
  'Aluminium Fabricators',
  'Aluminium Manufacturers & Suppliers',
  'Aluminium Suppliers',
  'Aluminium Windows',
  'Asbestos Removal',
  'Asphalt & Bitumen Paving',
  'Asphalt Products & Supplies',
  'Balustrading',
  'Bath Resurfacing',
  'Bathroom Accessories & Equipment',
  'Bathroom Equipment & Accessories Wholesalers & Manufacturers',
  'Bathroom Renovations & Designs',
  'Blinds Cleaning & Repair',
  'Boring & Drilling Contractors',
  'Brick Cleaning',
  'Brick Paving',
  'Bricks',
  'Cabinet Makers & Designers',
  'Cabinet Making Supplies',
  'Carpet & Carpet Tiles Wholesalers & Manufacturers',
  'Carpet & Rug Overlocking Services',
  'Carpet Cleaning & Protection',
  'Carpet Layers & Planners',
  'Carpet Repair',
  'Carpets & Rugs--Dyeing',
  'CCTV & Security Cameras',
  'Chimney Sweep',
  'Clean Room Installation & Maintenance',
  'Cleaning Cloth Supplies',
  'Cleaning Products & Supplies',
  'Commercial & Industrial Cleaning Services',
  'Commercial Building Maintenance',
  'Cool Room Builders & Construction',
  'Curtain Cleaning & Maintenance',
  'Domestic Services',
  'Door & Gate Operating Equipment',
  'Doors & Door Fittings',
  'Drainage & Drain Contractors',
  'Drainage Equipment & Systems',
  'Duct Cleaning',
  'Ducting & Ductwork',
  'Dust & Fume Extraction Systems',
  'Electric Power Lines',
  'Electrical Accessories Wholesalers & Manufacturers',
  'Electrical Appliance Wholesalers & Manufacturers',
  'Electrical Appliances Services & Parts',
  'Electrical Engineers',
  'Electrical Switchboard Manufacturers',
  'Electrical Switches & Control Equipment',
  'Electrical Test & Tag',
  'Electrical Testing Equipment',
  'Electrical Wholesalers',
  'Electricians & Electrical Contractors',
  'Electricity Suppliers',
  'Emergency Lighting & Power',
  'Erosion Control & Soil Stabilisation',
  'Fencing Contractors',
  'Fencing Materials',
  'Floor Covering Layers',
  'Floor Machines',
  'Floor Tiles & Wall Tiles',
  'Floor Treatment Products',
  'Fly Screens',
  'Gas Appliances',
  'Gas Burners',
  'Gas Cylinder Testing',
  'Gas, Oil & Fuel Companies',
  'Gates',
  'Gazebos & Shade Houses',
  'Glass Bricks & Accessories',
  'Glass Manufacturing & Processing',
  'Glazier & Glass Replacement Services',
  'Graffiti Removal',
  'Grease Trap Cleaning Services',
  'Gutter Cleaning',
  'Guttering & Spouting',
  'Heating Appliances & Systems',
  'Heating Appliances Repair & Service',
  'Home Air Conditioning',
  'Home Automation',
  'Home Cleaning',
  'Home Improvements',
  'Home Maintenance & Handymen',
  'Hot Water Systems',
  'Insulation Installers & Contractors',
  'Interior Decorators',
  'Interior Designers',
  'Ironing Services',
  'Kitchen Renovations & Designs',
  'Leadlight',
  'Lift Maintenance',
  'Lighting Consultants',
  'Lighting Maintenance',
  'Lighting Stores',
  'Lighting Wholesalers & Manufacturers',
  'Lightning & Surge Protection',
  'Lighting & Power Pole',
  'Lock Distributors & Manufacturers',
  'Locksmiths & Locksmith Services',
  'Locksmiths'' Supplies',
  'Mattress Cleaning',
  'Mirrors',
  'Organising Services--Home & Office',
  'Painters & Decorators',
  'Painters'' Supplies',
  'Paint & Painting Equipment',
  'Parquetry Flooring',
  'Pest Control',
  'Pipe Lining & Coating',
  'Plaster & Plastering Supplies',
  'Plasterers',
  'Plastering Supplies & Equipment',
  'Plumbers & Gas Fitters',
  'Plumbing Consultants',
  'Plumbing Supplies',
  'Pressure & Steam Cleaning Contractors',
  'Pressure & Steam Cleaning Equipment',
  'Protective Coatings',
  'Refrigeration Domestic & Retail',
  'Refrigeration Engineers',
  'Retail Insulation Materials',
  'Rising Damp - Repairs & Waterproofing',
  'Roller Shutters',
  'Safety Glass',
  'Security Doors, Windows & Equipment',
  'Security Guards',
  'Security Systems',
  'Septic Tank Cleaning',
  'Septic Tank Installation & Manufacturers',
  'Sewage & Waste Water Treatment',
  'Sewer Cleaning Equipment',
  'Shower Screens',
  'Skylights',
  'Slaters & Roof Tilers',
  'Soundproofing & Acoustic Insulation Services',
  'Splashbacks',
  'Stained Glass',
  'Swimming Pool Designs & Construction',
  'Swimming Pool Maintenance & Repairs',
  'Swimming Pool Safety Inspections',
  'Tennis Court Construction & Repairs',
  'Tiling Equipment & Supplies',
  'Timber Windows',
  'Ventilation System & Equipment',
  'Wall & Floor Tilers',
  'Wall Finishes',
  'Wallpapering & Wallcovering Services',
  'Water Tanks & Tank Supplies',
  'Water Treatment & Equipment',
  'Waterproofing Contractors',
  'Window Cleaning',
  'Window Repairs',
  'Window Tinting',
  'Windows--Steel',
  'Commercial Air Conditioning',
  'Commercial Kitchen Equipment',
  'Commercial & Industrial Refrigeration',
  'Range Hoods',
  'Stoves & Ranges',
  'Stove & Rangehood Parts & Service'
);
