-- GROUP 3: Automotive
UPDATE rawdata_yellowpage_new
SET category_group = 'Automotive'
WHERE category_name IN (
  '4WD & 4X4 Accessories',
  'Auto Electrician Services',
  'Auto Wreckers & Recyclers',
  'Brake & Clutch Services',
  'Brakes & Clutch Equipment Wholesalers & Manufacturers',
  'Car & Automotive Transmissions',
  'Car Accessories',
  'Car Air Conditioning',
  'Car Alarms',
  'Car Auctions',
  'Car Audio, Stereo & Radio',
  'Car Batteries & Car Battery Replacements',
  'Car Cleaning Products',
  'Car Detailing',
  'Car Driving &/or Pooling Services',
  'Car Insurance Providers',
  'Car Loans & Motor Vehicle Finance',
  'Car Paint',
  'Car Parking',
  'Car Parts',
  'Car Radiator Repair & Services',
  'Car Rental & Hire',
  'Car Restoration',
  'Car Transport',
  'Car Wash Services',
  'Caravan & Camper Trailer Repairs',
  'Diesel Engineers',
  'Diesel Engines, Parts & Equipment',
  'Diesel Fuel Injection',
  'Electronic Rust Protection & Rustproofing',
  'Engine Reconditioning',
  'Exhaust Systems & Mufflers',
  'Fuel Pumps & Carburettor Equipment',
  'LPG & Gas Conversions',
  'Mechanics & Motor Engineers',
  'Motor Body Builders',
  'Motor Vehicle Leasing',
  'Motorcycle Parts & Accessories Retailers',
  'Motorcycle Parts & Accessory Wholesalers & Manufacturers',
  'Motorcycle Tours & Hire',
  'Motorcycle Wreckers',
  'Motorsport Services',
  'New Car Dealers',
  'Panel Beater & Painters',
  'Panel Beating Supplies & Equipment',
  'Petrol Engines',
  'Petrol Fuel Injection',
  'Power Steering',
  'Roadside Assistance',
  'Service Stations',
  'Suspension, Shock Absorbers & Springs',
  'Towing Equipment',
  'Towing Services',
  'Truck & Bus Sales',
  'Truck Hire & Bus Hire',
  'Truck Parts',
  'Turbochargers',
  'Tyre Repairs, Retreading & Recapping',
  'Tyres',
  'Tyres--Retreading, Repairing &/or Changing Equipment',
  'Used Cars',
  'Vehicle Inspections',
  'Wheel Alignment & Wheel Balance',
  'Wheels & Rims',
  'Windscreens & Windscreen Repair',
  'Bus & Coach Charter & Tours',
  'Bus & Truck Repairs',
  'Bus Builders'
);
