-- GROUP 4: Healthcare & Medical
UPDATE rawdata_yellowpage_new
SET category_group = 'Healthcare & Medical'
WHERE category_name IN (
  'Anaesthesia',
  'Audiologist & Hearing Test',
  'Bariatric Surgery',
  'Cardiology',
  'Community Health Centres & Services',
  'Dental Equipment--Repairs',
  'Dental Health Aids',
  'Dental Hospital & Emergency Dental',
  'Dental Laboratories',
  'Dental Prosthetist',
  'Dental Supplies & Equipment',
  'Dental Technicians',
  'Dentist',
  'Dermatology',
  'Diagnostic Radiology',
  'Diagnostic Ultrasound',
  'Doctors-Medical Practitioners',
  'Endocrinology',
  'Endodontists',
  'Gastroenterology',
  'Gynaecological Oncology',
  'Hand Surgery',
  'Health Insurance',
  'Health Support Organisations',
  'Hire--Medical Equipment',
  'Home Health Care Equipment',
  'Hospitals--Public',
  'Infertility Services (Including IVF)',
  'Medical Agents',
  'Medical Centres',
  'Medical Equipment & Repairs',
  'Medical Oncology',
  'Medical Research',
  'Medical Supplies',
  'Obstetrics & Gynaecology',
  'Occupational & Environmental Medicine',
  'Ophthalmology',
  'Optical Prescription Dispensers',
  'Optical Supplies',
  'Optometrist',
  'Oral & Maxillofacial Surgeons (Dental)',
  'Oral Pathology & Oral Medicine Specialists',
  'Oral Surgeons',
  'Orthodontist',
  'Orthodontists (Specialty)',
  'Orthopaedic Footwear & Custom Shoes',
  'Orthopaedic Surgery',
  'Otolaryngology (Ear, Nose & Throat)',
  'Paediatric Dentists',
  'Paediatric Medicine',
  'Palliative Care',
  'Pathology Laboratories',
  'Periodontists',
  'Pharmaceutical Products Wholesalers & Manufacturers',
  'Pharmacists--Consultant',
  'Plastic & Reconstructive Surgery',
  'Private Hospitals',
  'Prosthodontists',
  'Psychiatry',
  'Rehabilitation Medicine',
  'Rehabilitation Services',
  'Skin Cancer Clinic',
  'Sports Medicine',
  'Surgery-General',
  'Travel Health',
  'Urology',
  'Vascular Surgery',
  'Chemist & Pharmacy Stores',
  'Chemists--Consulting & Industrial',
  'Chemists'' Supplies',
  'X-Ray Equipment & Supplies',
  'Vets & Veterinary Surgeons',
  'Veterinary Animal Clinics & Hospitals',
  'Veterinary Laboratories',
  'Veterinary Supplies & Instruments'
);
