-- GROUP 5: Allied Health & Wellness
UPDATE rawdata_yellowpage_new
SET category_group = 'Allied Health & Wellness'
WHERE category_name IN (
  'Acupuncture',
  'Alcohol & Drug Counselling',
  'Alternative & Natural Therapies',
  'Alternative Health Therapies Courses',
  'Aromatherapy',
  'Bowen Therapy',
  'Chinese Medicine',
  'Chiropractor',
  'Colonic Irrigation',
  'Dietitians',
  'Exercise Physiologists',
  'Feldenkrais',
  'Health & Fitness - Centres & Services',
  'Health Food Stores',
  'Health Foods & Products Wholesalers & Manufacturers',
  'Herbalists',
  'Homeopathy',
  'Kinesiology',
  'Life Coach',
  'Massage Tables & Equipment',
  'Massage Therapy',
  'Massage Therapy Courses',
  'Meditation',
  'Myotherapy',
  'Naturopaths',
  'Occupational Therapist',
  'Osteopath',
  'Physiotherapist',
  'Physiotherapy Equipment',
  'Pilates',
  'Podiatrist',
  'Podiatry Supplies',
  'Psychologist',
  'Psychotherapists',
  'Reflexology',
  'Reiki',
  'Relaxation Therapy',
  'Shiatsu Therapy',
  'Skin Treatments & Skin Clinics',
  'Vitamin Products',
  'Weight Loss Treatments',
  'Marriage, Family & Personal Counselling'
);
