-- GROUP 7: Food & Hospitality
UPDATE rawdata_yellowpage_new
SET category_group = 'Food & Hospitality'
WHERE category_name IN (
  'Bakers',
  'Bakery Equipment',
  'Bars',
  'Bars--Domestic & Commercial',
  'Bottle Shop & Liquor Store',
  'Butcher Supplies',
  'Butchers Shop',
  'Cafes',
  'Cake & Pastry Shops',
  'Cake Decorating Supplies',
  'Cake Decorators & Decorating Classes',
  'Catering',
  'Catering & Food Consultants',
  'Catering Equipment Hire',
  'Catering Supplies',
  'Chocolate & Cocoa',
  'Coffee Retailers',
  'Confectionery & Lolly Shop',
  'Delicatessens',
  'Dishwasher Service & Parts',
  'Dishwashers',
  'Dispensing Equipment, Supplies & Service',
  'Egg Merchants',
  'Fast Food',
  'Fish & Seafood',
  'Fish & Seafood Production &/or Processing',
  'Food &/or General Store Supplies',
  'Food &/or General Stores',
  'Food Brokers & Agents',
  'Food Delicacies',
  'Food Product Processors & Manufacturers',
  'Frozen Food Wholesalers & Manufacturers',
  'Frozen Foods--Retail',
  'Fruit &/or Berry Growers',
  'Fruit Shops & Greengrocers',
  'Hotel & Motel Brokers',
  'Hotel, Bar & Restaurant Supplies',
  'Hotels & Accommodation',
  'Ice Cream--Retail',
  'Ice Making Machine',
  'Milk Vendors',
  'Motel Supplies & Equipment',
  'Motels',
  'Organic Products',
  'Oyster Suppliers & Farmers',
  'Pizza Restaurants',
  'Poultry--Retail',
  'Pubs',
  'Restaurants',
  'Smallgoods Wholesalers & Manufacturers',
  'Supermarkets & Grocery Stores',
  'Theatre Restaurants',
  'Wholesale Butchers',
  'Wholesale Cakes & Pastries',
  'Wholesale Coffee',
  'Wholesale Grain & Produce',
  'Wholesale Seafood & Fish',
  'Wine Merchants & Spirit Dealers',
  'Wine Racks & Storage',
  'Wineries & Vineyards'
);
