-- GROUP 8: Retail & Shopping
UPDATE rawdata_yellowpage_new
SET category_group = 'Retail & Shopping'
WHERE category_name IN (
  'Antiques - Auctions & Dealers',
  'Antiques Reproduction & Restoration',
  'Aquariums & Aquarium Supplies',
  'Art Dealers',
  'Art Supplies',
  'Artificial Flowers & Plants',
  'Baby Prams, Furniture & Accessories',
  'BBQ & Barbecue Equipment',
  'Beds & Bedding Stores',
  'Bicycle Accessories & Repairs',
  'Bicycles & Accessories Wholesalers & Manufacturers',
  'Book Stores & Shops',
  'Books Online',
  'Boutiques',
  'Bridal Dresses & Accessories',
  'Camping Gear & Outdoor Equipment',
  'Camper Trailers & Caravans',
  'Camper Trailers & Caravan Hire',
  'Campervans & Motor Homes',
  'Caravan Parks',
  'Christmas Trees & Decorations',
  'Clocks & Repairs',
  'Clothes Online',
  'Clothing Alterations & Mending',
  'Clothing Pattern Services',
  'Clothing--Custom Made',
  'Coin & Note Changing Equipment',
  'Craft Supplies & Craft Shop',
  'Department Stores',
  'Discount Stores',
  'Dress Patterns & Dressmakers'' Models',
  'Dressmakers',
  'Electrical & Home Appliance Stores',
  'Embroidery',
  'Embroidery Supplies & Equipment',
  'Fabrics-Knitted or Woven',
  'Fashion Accessories',
  'Fashion Agents',
  'Fashion Jewellery',
  'Fireplaces & Fireplace Accessories',
  'Fitness Equipment',
  'Florist Supplies',
  'Florists',
  'Furnishings--Retail',
  'Furnishings--W''sale',
  'Furniture & Appliance Hire',
  'Furniture Assembly Services',
  'Furniture Design & Custom Furniture',
  'Furniture Manufacturers & Wholesalers',
  'Furniture Manufacturers Supplies',
  'Furniture Restoration & Repairs',
  'Furniture Stores & Shops',
  'Gem Merchants',
  'Gift Baskets & Hampers',
  'Gift Shop',
  'Gift Shop Supplies',
  'Gold & Silver Merchants',
  'Hardware Store',
  'Hardware--W''sale',
  'Hi-Fi Equipment',
  'Hi-Fi Equipment & Service',
  'Home Cinema & Theatre',
  'Jewellery Designers',
  'Jewellery Stores',
  'Jewellery Valuation',
  'Ladies'' Wear-Retail',
  'Lottery Agents',
  'Mattresses',
  'Microwave Oven',
  'Mobile Phones & Accessories',
  'Mobile Phone Repairs & Service',
  'Music & Musical Instruments',
  'Music Stores-Retail',
  'Musical Instrument Makers & Repairers',
  'Newsagents',
  'Office & Business Systems',
  'Office Furniture',
  'Office Supplies',
  'Opals',
  'Oriental Rugs & Handmade Carpets',
  'Outdoor Furniture',
  'Pawn Shop & Pawnbrokers',
  'Pet Shops'' Suppliers',
  'Pet Supplies & Pet Food',
  'Pet Warehouse - Shops & Stores',
  'Pianos, Keyboards & Organs',
  'Point of Sale (POS) Systems & Service',
  'Recycled Clothing',
  'Second Hand Books & Antiquarian',
  'Second Hand Dealers',
  'Second Hand Furniture',
  'Sewing Machines',
  'Sewing Machine Repairs & Service',
  'Shopping Centres & Malls',
  'Signwriters',
  'Sports Equipment, Goods & Repairs',
  'Stamp Collectors & Dealers',
  'Stationery',
  'Tailors--Ladies''',
  'Tailors-Men''s',
  'Television Retailers',
  'Toys--Retail & Repairs',
  'Toy Manufacturers',
  'TV Antenna Services',
  'TV Hire',
  'TV Repairs & Installation',
  'Vacuum Cleaner Parts & Repairs',
  'Vacuum Cleaners',
  'Video & DVD Equipment--Repairs & Service',
  'Washing Machines & Dryer Repairs, Service & Parts',
  'Washing Machines & Dryers - Commercial & Industrial',
  'Washing Machines & Dryers - Domestic',
  'Watch Shop & Watch Repairs',
  'Watches--W''sale',
  'Watchmakers'' Equipment & Supplies',
  'Wholesale Florist',
  'Wholesale Jewellery',
  'Wholesale Toys',
  'Wholesale Tyres',
  'Neon & LED Signs',
  'New Age Products & Services',
  'Fridge Repairs'
);
