-- GROUP 9: Professional Services
UPDATE rawdata_yellowpage_new
SET category_group = 'Professional Services'
WHERE category_name IN (
  'Accountants & Auditors',
  'Architects',
  'Barristers (All states except TAS)',
  'Barristers & Solicitors (TAS only)',
  'Business & Professional Organisations',
  'Business Consultants',
  'Business Law',
  'Business Records Management',
  'Business Systems Consultants',
  'Civil Litigation',
  'Commercial Law',
  'Conveyancer & Conveyancing Services',
  'Conveyancing & Property Law',
  'Criminal Law',
  'Customs Brokers',
  'Debt Collection',
  'Engineering Consultants & Services',
  'Environmental Consultants',
  'Export Agents',
  'Family Law',
  'Financial Planning',
  'Forensic Services',
  'Franchises & Franchising',
  'Importers & Imported Products',
  'Insurance Agents',
  'Land Surveyors',
  'Lawyers & Solicitors',
  'Legal Support & Referral Services',
  'Management Consultants',
  'Marketing Consultants & Services',
  'Mediation',
  'Mediators',
  'Migration Agents & Services',
  'Packaging Consultants',
  'Patent Attorneys',
  'Personal Injury Lawyers',
  'Property Consultants',
  'Public Notary',
  'Retirement Planning & Advisory Services',
  'Settlement Agents (WA & NT only)',
  'Shelf Company Services',
  'Small Business Advisory Services',
  'Superannuation Fund, Annuity & Rollover Consultants',
  'Tax Agents',
  'Town & Regional Planning',
  'Trade Mark Registration & Investigation',
  'Trademark Attorneys',
  'Trustee Services',
  'Wills, Probates & Estates',
  'Workers Compensation'
);
