-- GROUP 11: Transport & Logistics
UPDATE rawdata_yellowpage_new
SET category_group = 'Transport & Logistics'
WHERE category_name IN (
  'Air Cargo Services',
  'Aircraft Charter & Hire',
  'Airlines & Travel Agents',
  'Airport Bus & Shuttles',
  'Airports &/or Airport Services',
  'Armoured Car Services',
  'Boat & Yacht Transport Services',
  'Cold Storage',
  'Courier Services',
  'Crane Hire',
  'Elevated Work Platform Hire',
  'Forklift Licence & Plant Operator Training',
  'Forklifts & Forklift Repairs',
  'Freight & Cargo Services',
  'Freight & Transport Companies',
  'Furniture Removalists & Movers',
  'Heavy Haulage',
  'Helicopters',
  'Limo Hire',
  'Pallets & Platforms',
  'Piano Removals',
  'Railway Construction, Equipment & Materials',
  'Railway Services',
  'Refrigerated Transport Services',
  'Refrigerated Transport Vans & Trucks',
  'Road Transport Vehicles &/or Equipment',
  'Shipping Agents & Freight Companies',
  'Storage--Liquid--Bulk',
  'Taxi',
  'Taxi Truck',
  'Tipper Truck Contractors',
  'Trailer Hire',
  'Transport - Light',
  'Transport Companies & Freight Forwarding Agents',
  'Transport Depots',
  'Transport Escort & Pilot Services',
  'Transportation Consultants',
  'Water Cartage',
  'Water Taxis'
);
