-- GROUP 12: Agriculture & Rural
UPDATE rawdata_yellowpage_new
SET category_group = 'Agriculture & Rural'
WHERE category_name IN (
  'Abattoirs',
  'Aerial Agricultural Services',
  'Animal & Pet Enclosures',
  'Animal Welfare',
  'Artificial Breeding Services',
  'Bird Breeders & Dealers',
  'Cattery',
  'Dog & Cat Clipping & Grooming',
  'Dog & Cat Minding - In Home',
  'Dog Boarding Kennels',
  'Dog Breeders',
  'Dog Training',
  'Dogs'' Supplies',
  'Emu & Ostrich Farmers & Products',
  'Farm & Agricultural Advisory Services',
  'Farm & Agricultural Machinery',
  'Farm Contracting Services',
  'Farm Supplies & Farming Equipment',
  'Farmers',
  'Fertiliser & Insecticide',
  'Fertilisers',
  'Game Farmers & Dealers',
  'Grain & Produce',
  'Graziers',
  'Herbs (Nurseries-Retail)',
  'Horse Dentists',
  'Horse Riding',
  'Horse Transport',
  'Horticultural Consultants',
  'Insect Control Equipment',
  'Insecticides, Herbicides & Fungicides',
  'Livestock Buyers',
  'Livestock Transport Services',
  'Pet Care',
  'Pet Cemetery & Crematorium',
  'Pet Transport Services',
  'Poultry Farmers & Dealers',
  'Poultry Supplies',
  'Saddlery & Riding',
  'Seed Cleaning, Drying & Grading',
  'Seed Suppliers',
  'Sheep Shearing Contractors',
  'Stock & Station Agents',
  'Stock Feeds, Fodder & Supplements',
  'Traps--Animal Or Rodent',
  'Weed Control Services',
  'Bee & Wasp Removal'
);
