-- GROUP 14: Entertainment & Recreation
UPDATE rawdata_yellowpage_new
SET category_group = 'Entertainment & Recreation'
WHERE category_name IN (
  'Adult Services & Entertainment',
  'Adult Shops & Stores',
  'Amusement Equipment & Hire',
  'Amusement Machines--Coin Operated',
  'Astrology',
  'AV Equipment & Production',
  'Boat & Yacht Builders & Repairers',
  'Boat & Yacht Equipment',
  'Boat Hire',
  'Boat Motors & Outboards',
  'Bowling Club',
  'Camps',
  'Cinemas',
  'Conference Venues',
  'Country Music Clubs',
  'Coursing & Kennel Clubs',
  'DJs - Mobile',
  'Event Management',
  'Fencing Clubs',
  'Fishing Bait',
  'Fishing Tackle',
  'Fishing Trips',
  'Function Rooms & Party Venues',
  'Gaming Machines & Supplies',
  'Go-Karts & Karting Supplies',
  'Golf Clubs - Private',
  'Golf Driving Range',
  'Internet Cafes',
  'Jukeboxes',
  'Jumping Castles Hire',
  'Lawn Mowing Services',
  'Lawn Mower Shops & Repairs',
  'Lawn Mowers Wholesalers & Manufacturers',
  'Garden Nurseries',
  'Garden Pots',
  'Garden Supplies & Equipment',
  'Gardeners',
  'Gardening Clubs',
  'Indoor Plant Hire',
  'Irrigation & Reticulation Systems',
  'Land Clearing & Firebreak Contractors',
  'Landscape Architects',
  'Landscape Supplies',
  'Landscaping & Landscape Design',
  'Music Amplification Equipment & Services',
  'Music Arrangers & Composers',
  'Music Therapists',
  'Music-Background',
  'Music-Sheet',
  'Musicians & Musicians'' Agents',
  'Organs & Keyboards-Tuning & Repairing',
  'Parks, Gardens & Reserves',
  'Party Balloons & Printed Balloons',
  'Party Equipment Hire',
  'Pay Television',
  'Personal Trainers & Fitness Training',
  'Piano Tuning & Piano Repair',
  'Pipe Organ Builders, Tuners & Restorers',
  'Psychic & Clairvoyant',
  'Public Address (PA) Sound Systems',
  'Public Golf Courses',
  'Publishers--Music',
  'Radio Communications Equipment & Service',
  'Roses',
  'Rugby League Clubs',
  'Satellite Equipment & Services',
  'Slashing Contractors',
  'Social & General Clubs',
  'Television Stations',
  'Theatres & Theatre Companies',
  'Tourist Attractions & Information',
  'Travel Agents',
  'Tree & Stump Removal Services',
  'Tree Surgery',
  'Turf & Lawn Suppliers',
  'Water Features, Ponds & Garden Ornaments',
  'Wedding Cakes',
  'Wedding Cars',
  'Wedding Flowers',
  'Wedding Gifts & Registry Services',
  'Wedding Hair & Beauty Services',
  'Wedding Jewellery & Accessories',
  'Wedding Music & Entertainment',
  'Wedding Photographers',
  'Wedding Planning & Planners',
  'Wedding Venues',
  'Arboriculturists',
  'Rotary Hoeing',
  'Nursery & Garden Supplies Wholesale',
  'Nursery Supplies',
  'Advanced Shrubs & Trees (Nurseries-Retail)'
);
