-- GROUP 15: Industrial & Manufacturing
UPDATE rawdata_yellowpage_new
SET category_group = 'Industrial & Manufacturing'
WHERE category_name IN (
  'Abrasive Blasting',
  'Air & Gas Cylinders',
  'Automation Systems & Equipment',
  'Balancing Equipment & Services',
  'Battery Charging Equipment',
  'Bearings & Bushings',
  'Bitumen Spraying',
  'Chainsaws & Brush Cutters',
  'Coach & Carriage Builders & Dealers',
  'Communication Antennas',
  'Compressed Air Control Equipment',
  'Computer Laptop Hire & Leasing',
  'Computer Networking & Installation',
  'Computer Parts & Equipment',
  'Cork Merchants',
  'Crushers & Crushing Services',
  'Data Communications',
  'Designing Engineers',
  'Distilled Water',
  'Drinking Water Supplies & Accessories',
  'Electric Motor Repairs & Generator Repairs',
  'Electric Motors',
  'Engineering & Engineers',
  'Engineering & Mining Surveyors',
  'Engineering Supplies',
  'Ergonomics',
  'Excavation & Earth Moving Equipment',
  'Excavation & Earthmoving Contractors',
  'Factory & Workshop Equipment Hire',
  'Fans & Blowers',
  'Fax Equipment, Supplies & Service',
  'Fibre & Cardboard Boxes',
  'Fibre Optics',
  'Filtering Materials & Supplies',
  'Filters & Filter Service',
  'Firewood',
  'Generators',
  'Glass Processing & Handling Equipment',
  'Glass Washing Machines',
  'Hoses & Hose Fittings',
  'Hydraulic Equipment & Supplies',
  'Hydroponics & Hydroponic Equipment',
  'Industrial Capacitors',
  'Industrial Drying Equipment & Services',
  'Industrial Sewing Machines',
  'Inspection & Testing Services',
  'Installation & Maintenance Engineers',
  'Instrument Cases',
  'Internet Marketing Services',
  'Jacks',
  'Ladders, Step Ladders & Trestles',
  'Laser Cutting Services',
  'Laundries',
  'Laundromat & Self Service Laundries',
  'Commercial Laundry Equipment & Supplies',
  'Linen Hire',
  'Lime',
  'Mailing Machines & Equipment',
  'Manufacturers'' Agents',
  'Manufacturing Engineers',
  'Marble & Granite Suppliers',
  'Marine Engineers',
  'Measuring Machines & Equipment',
  'Mechanical Engineer',
  'Metal Polishing',
  'Metal Recyclers & Merchants',
  'Mining Contractors',
  'Mining, Quarrying Equipment & Supplies',
  'Mobile Marketing',
  'Natural Stone Products & Supplies',
  'Nuts & Bolts',
  'OHS - Occupational Health & Safety',
  'Oil & Mechanical Seals',
  'Overall Hire Services',
  'Packaging Supplies & Materials',
  'Particle Board',
  'Plastic Bags',
  'Plastic Fabrication',
  'Plywood & Veneers',
  'Portable Toilets',
  'Post Hole Contractors & Equipment',
  'Power Tools & Repairs',
  'Printers & Printing Services',
  'Pump Manufacturers, Sales & Service',
  'Pumping Contractors',
  'Quarries',
  'Rechargeable Batteries & Dry Cell Battery',
  'Recycling & Waste Management Equipment',
  'Recycling Depots Beverage Containers ( S.A. & NT. Only )',
  'Recycling Services',
  'Refrigeration Parts & Equipment Wholesaler & Manufacturer',
  'Rubber Products',
  'Rubbish Removal & Skip Bins',
  'Safes & Vaults',
  'Sand, Soil & Gravel Supplies',
  'Sand, Soil & Gravel Wholesalers',
  'Sawdust & Shaving Suppliers',
  'Sawmills',
  'Saws',
  'Scrap Metal Merchants',
  'Sealing Compounds & Services',
  'Second Hand Cardboard Boxes & Cartons',
  'Second Hand Machinery',
  'Sewing Contractors--Industrial',
  'Sharpening Service',
  'Shavers',
  'Shavers -- Electric -- Repairs',
  'Sheet Metal Fabricators',
  'Shelving Solutions',
  'Shelving Units & Racks',
  'Ship Builders & Repairers',
  'Soil Testing',
  'Solar Energy',
  'Spray Painting',
  'Stainless Steel Products & Equipment Suppliers',
  'Steel Wool Wholesalers & Manufacturers',
  'Tank Cleaning',
  'Tarpaulins',
  'Telephone Installation, Repairs & Maintenance',
  'Telephone Systems & Equipment',
  'Telephones & Accessories',
  'Timber Logging',
  'Tools & Trade Tools',
  'Underground Penetrating Radar & Locators',
  'Vending Machines',
  'Waste Disposal & Reduction Services',
  'Water Coolers',
  'Welding',
  'Welding Supplies & Equipment',
  'Wood Benders & Carvers',
  'Wood Chippers',
  'Wooden Boxes & Cases',
  'Work & Corporate Uniform Hire',
  'Disposable Paper Products',
  'Document Shredding',
  'Nurses & Nursing Services',
  'Aged Care Services & Homes',
  'Disability Services & Care Organisations',
  'Hire--Nursery Equipment',
  'Nappy Services'
);
