import { getCompanyDbClient } from '../db/supabase';

export interface CreateCampaignData {
  name: string;
  serviceDescription: string;
  emailTone: 'professional' | 'friendly' | 'casual' | 'formal' | 'enthusiastic';
  businessIds?: number[];
  manualEmail?: string;
  manualName?: string;
}

export interface UpdateCampaignData {
  name?: string;
  subject?: string;
  senderName?: string;
  senderEmail?: string;
  serviceDescription?: string;
  tone?: 'professional' | 'friendly' | 'casual';
}

export interface Campaign {
  id: number;
  organization_id: string;
  name: string;
  subject: string;
  sender_name: string;
  sender_email: string;
  service_description: string;
  tone: string;
  status: string;
  total_recipients: number;
  sent_count: number;
  generated_count: number;
  failed_count: number;
  target_list_id: number | null;
  created_at: string;
  updated_at: string;
}

export class CampaignServiceSupabase {
  private get supabase() {
    return getCompanyDbClient();
  }

  /**
   * Create a new campaign
   */
  async createCampaign(organizationId: string, data: CreateCampaignData) {
    const { name, serviceDescription, emailTone, businessIds, manualEmail, manualName } = data;

    try {
      // If manual email is provided, create a manual campaign
      if (manualEmail) {
        // Create campaign
        const { data: campaign, error: campaignError } = await this.supabase
          .from('campaigns')
          .insert({
            organization_id: organizationId,
            name,
            subject: 'Generated by AI',
            sender_name: 'Your Company',
            sender_email: process.env.FROM_EMAIL || 'onboarding@resend.dev',
            service_description: serviceDescription,
            tone: emailTone,
            total_recipients: 1,
            status: 'draft',
          })
          .select()
          .single();

        if (campaignError) throw campaignError;

        // Create campaign item for manual entry
        const { error: itemError } = await this.supabase
          .from('campaign_items')
          .insert({
            campaign_id: campaign.id,
            business_id: null,
            status: 'pending',
            metadata: {
              name: manualName || 'Valued Client',
              email: manualEmail,
            },
          });

        if (itemError) throw itemError;

        return this.mapCampaignToResponse(campaign);
      }

      // Validate business IDs for normal mode
      if (!businessIds || businessIds.length === 0) {
        throw new Error('Business IDs are required');
      }

      // Validate businesses exist
      const { data: validBusinesses, error: businessError } = await this.supabase
        .from('rawdata_yellowpage_new')
        .select('listing_id')
        .in('listing_id', businessIds);

      if (businessError) throw businessError;

      if (!validBusinesses || validBusinesses.length !== businessIds.length) {
        throw new Error('Some business IDs are invalid');
      }

      // Create campaign
      const { data: campaign, error: campaignError } = await this.supabase
        .from('campaigns')
        .insert({
          organization_id: organizationId,
          name,
          subject: 'Generated by AI',
          sender_name: 'Your Company',
          sender_email: process.env.FROM_EMAIL || 'onboarding@resend.dev',
          service_description: serviceDescription,
          tone: emailTone,
          total_recipients: businessIds.length,
          status: 'draft',
        })
        .select()
        .single();

      if (campaignError) throw campaignError;

      // Create campaign items
      const campaignItems = businessIds.map((businessId) => ({
        campaign_id: campaign.id,
        business_id: businessId,
        status: 'pending',
      }));

      const { error: itemsError } = await this.supabase
        .from('campaign_items')
        .insert(campaignItems);

      if (itemsError) throw itemsError;

      return this.mapCampaignToResponse(campaign);
    } catch (error) {
      console.error('Campaign Create Error:', error);
      throw error;
    }
  }

  /**
   * Get campaigns for an organization
   */
  async getCampaigns(organizationId: string, page = 1, limit = 20) {
    const offset = (page - 1) * limit;

    // Get campaigns
    const { data: campaigns, error: campaignsError } = await this.supabase
      .from('campaigns')
      .select('*')
      .eq('organization_id', organizationId)
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    if (campaignsError) throw campaignsError;

    // Get total count
    const { count, error: countError } = await this.supabase
      .from('campaigns')
      .select('*', { count: 'exact', head: true })
      .eq('organization_id', organizationId);

    if (countError) throw countError;

    const total = count || 0;

    return {
      campaigns: (campaigns || []).map(this.mapCampaignToResponse),
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  /**
   * Get campaign by ID with organization isolation
   */
  async getCampaign(organizationId: string, campaignId: number) {
    const { data: campaign, error } = await this.supabase
      .from('campaigns')
      .select('*')
      .eq('id', campaignId)
      .eq('organization_id', organizationId)
      .single();

    if (error) {
      if (error.code === 'PGRST116') return null; // Not found
      throw error;
    }

    return this.mapCampaignToResponse(campaign);
  }

  /**
   * Get campaign with items and metrics
   */
  async getCampaignWithDetails(organizationId: string, campaignId: number) {
    const campaign = await this.getCampaign(organizationId, campaignId);
    if (!campaign) return null;

    // Get campaign items with business details
    const { data: items, error: itemsError } = await this.supabase
      .from('campaign_items')
      .select(`
        id,
        status,
        email_subject,
        email_content,
        sent_at,
        error_message,
        metadata,
        business_id,
        rawdata_yellowpage_new (
          company_name,
          email,
          address_suburb,
          category_name
        )
      `)
      .eq('campaign_id', campaignId);

    if (itemsError) throw itemsError;

    // Map items
    const mappedItems = (items || []).map((item: any) => ({
      id: item.id,
      status: item.status,
      emailSubject: item.email_subject,
      emailContent: item.email_content,
      sentAt: item.sent_at,
      errorMessage: item.error_message,
      metadata: item.metadata,
      businessId: item.business_id,
      businessName: item.rawdata_yellowpage_new?.company_name || null,
      businessEmail: item.rawdata_yellowpage_new?.email || null,
      businessCity: item.rawdata_yellowpage_new?.address_suburb || null,
      businessIndustry: item.rawdata_yellowpage_new?.category_name || null,
    }));

    // Get metrics
    const metrics = await this.getCampaignMetrics(organizationId, campaignId);

    return {
      ...campaign,
      items: mappedItems,
      metrics,
    };
  }

  /**
   * Update campaign
   */
  async updateCampaign(organizationId: string, campaignId: number, data: UpdateCampaignData) {
    const updateData: Record<string, any> = {
      updated_at: new Date().toISOString(),
    };

    if (data.name !== undefined) updateData.name = data.name;
    if (data.subject !== undefined) updateData.subject = data.subject;
    if (data.senderName !== undefined) updateData.sender_name = data.senderName;
    if (data.senderEmail !== undefined) updateData.sender_email = data.senderEmail;
    if (data.serviceDescription !== undefined) updateData.service_description = data.serviceDescription;
    if (data.tone !== undefined) updateData.tone = data.tone;

    const { data: campaign, error } = await this.supabase
      .from('campaigns')
      .update(updateData)
      .eq('id', campaignId)
      .eq('organization_id', organizationId)
      .select()
      .single();

    if (error) throw error;
    if (!campaign) throw new Error('Campaign not found');

    return this.mapCampaignToResponse(campaign);
  }

  /**
   * Delete campaign
   */
  async deleteCampaign(organizationId: string, campaignId: number) {
    const { error } = await this.supabase
      .from('campaigns')
      .delete()
      .eq('id', campaignId)
      .eq('organization_id', organizationId);

    if (error) throw error;
  }

  /**
   * Update campaign status
   */
  async updateCampaignStatus(organizationId: string, campaignId: number, status: string) {
    const { error } = await this.supabase
      .from('campaigns')
      .update({
        status,
        updated_at: new Date().toISOString(),
      })
      .eq('id', campaignId)
      .eq('organization_id', organizationId);

    if (error) throw error;
  }

  /**
   * Get campaign metrics
   */
  async getCampaignMetrics(organizationId: string, campaignId: number) {
    // Get status counts
    const { data: items, error } = await this.supabase
      .from('campaign_items')
      .select('status')
      .eq('campaign_id', campaignId);

    if (error) throw error;

    const metricsMap: Record<string, number> = {};
    (items || []).forEach((item: { status: string }) => {
      metricsMap[item.status] = (metricsMap[item.status] || 0) + 1;
    });

    const total = items?.length || 0;

    return {
      total,
      pending: metricsMap['pending'] || 0,
      generated: metricsMap['generated'] || 0,
      sent: metricsMap['sent'] || 0,
      failed: metricsMap['failed'] || 0,
      suppressed: metricsMap['suppressed'] || 0,
    };
  }

  /**
   * Get campaign analytics with email events
   */
  async getCampaignAnalytics(organizationId: string, campaignId: number) {
    const { data: events, error } = await this.supabase
      .from('email_events')
      .select('event_type')
      .eq('campaign_id', campaignId)
      .eq('organization_id', organizationId);

    if (error) throw error;

    const eventsMap: Record<string, number> = {};
    (events || []).forEach((event: { event_type: string }) => {
      eventsMap[event.event_type] = (eventsMap[event.event_type] || 0) + 1;
    });

    return {
      delivered: eventsMap['delivered'] || 0,
      opened: eventsMap['opened'] || 0,
      clicked: eventsMap['clicked'] || 0,
      bounced: eventsMap['bounced'] || 0,
      complained: eventsMap['complained'] || 0,
    };
  }

  /**
   * Map database campaign to response format (snake_case to camelCase)
   */
  private mapCampaignToResponse(campaign: any) {
    return {
      id: campaign.id,
      organizationId: campaign.organization_id,
      name: campaign.name,
      subject: campaign.subject,
      senderName: campaign.sender_name,
      senderEmail: campaign.sender_email,
      serviceDescription: campaign.service_description,
      tone: campaign.tone,
      status: campaign.status,
      totalRecipients: campaign.total_recipients,
      sentCount: campaign.sent_count,
      generatedCount: campaign.generated_count,
      failedCount: campaign.failed_count,
      targetListId: campaign.target_list_id,
      createdAt: campaign.created_at,
      updatedAt: campaign.updated_at,
    };
  }
}

export const campaignService = new CampaignServiceSupabase();
